apiVersion: v1
kind: Pod
metadata:
  name: config-secret-pod
spec:
  containers:
  - name: content
    image: busybox
    command: [ "sh", "-c"]
    args:
    - while true; do
        echo -en '\n';
        echo Current environment is `cat /configurations/environment`;
        echo Used token is `cat /secrets/token`;
        sleep 10;
      done;
    volumeMounts:
    - name: config-volume
      mountPath: "/configurations"
    - name: secret-volume
      mountPath: "/secrets"
  volumes:
  - name: config-volume
    configMap:
      name: app-config
  - name: secret-volume
    secret:
      secretName: token