apiVersion: apps/v1
kind: Deployment
metadata:
  name: metric-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: metric
  template:
    metadata:
      annotations:
        prometheus.io/scrape: "true"
      labels:
        app: metric
    spec:
      containers:
      - image: suakbas/lesson09:v1
        imagePullPolicy: Always
        name: metric
        ports:
        - containerPort: 3000

---

apiVersion: v1
kind: Service
metadata:
  name: metric-svc
spec:
  ports:
  - port: 3000
  selector:
    app: metric
