apiVersion: v1
kind: Pod
metadata:
  name: test-config-pod
spec:
  containers:
  - name: test
    image: busybox
    command:
      - sleep
      - "99999"
    env:
      - name: ENVIRONMENT
        valueFrom:
          configMapKeyRef:
            name: app-config
            key: environment
    volumeMounts:
    - name: config-volume
      mountPath: "/configurations"
  volumes:
  - name: config-volume
    configMap:
      name: app-config-file

